name: AntiGuest
main: de.codeinfection.quickwango.AntiGuest.AntiGuest
version: "${project.version}"
authors:
  - "Quick_Wango"
description: "Prevents guests from griefing."
website: "http://parallel-universe.de"
permissions:
  antiguest.*:
    description: "Allows the player to do everything"
    default: op
    children:
      antiguest.preventions.*: true
      antiguest.commands.*: true
  antiguest.preventions.*:
    description: "Allows the player to pass every prevention"
    default: op
    children:
      antiguest.preventions.actions.*: true
      antiguest.preventions.items.*: true
  antiguest.preventions.actions.*:
    description: "Allows the player to do all prevented actions"
    default: op
    children:
      antiguest.preventions.actions.build: true
      antiguest.preventions.actions.interact: true
      antiguest.preventions.actions.craft: true
      antiguest.preventions.actions.fight: true
      antiguest.preventions.actions.item: true
      antiguest.preventions.actions.vehicle: true
      antiguest.preventions.actions.spam: true
      antiguest.preventions.actions.chat: true
      antiguest.preventions.actions.music: true
  antiguest.preventions.items.*:
    description: "Allows the player to use all items"
    default: op
  antiguest.preventions.actions.build:
    description: "Allows the player to build"
    default: op
    children:
      antiguest.preventions.actions.placeblock: true
      antiguest.preventions.actions.breakblock: true
  antiguest.preventions.actions.craft:
    description: "Allows the player to do crafting related things"
    default: op
    children:
      antiguest.preventions.actions.furnace: true
      antiguest.preventions.actions.workbench: true
      antiguest.preventions.actions.dispenser: true
      antiguest.preventions.actions.chest: true
      antiguest.preventions.actions.inventory: true
      antiguest.preventions.actions.brew: true
      antiguest.preventions.actions.enchant: true
  antiguest.interact:
    description: "Allows the player to interact with the world"
    default: op
    children:
      antiguest.preventions.actions.lever: true
      antiguest.preventions.actions.button: true
      antiguest.preventions.actions.door: true
      antiguest.preventions.actions.bed: true
      antiguest.preventions.actions.fish: true
      antiguest.preventions.actions.bucket: true
      antiguest.preventions.actions.cake: true
      antiguest.preventions.actions.pressureplate: true
      antiguest.preventions.actions.repeater: true
  antiguest.preventions.actions.item:
    description: "Allows the player to do item related things"
    default: op
    children:
      antiguest.preventions.actions.pickup: true
      antiguest.preventions.actions.drop: true
  antiguest.preventions.actions.fight:
    description: "Allows the player to fight"
    default: op
    children:
      antiguest.pvp: true
      antiguest.monster: true
  antiguest.preventions.actions.movement:
    description: "Allows the player to move as he wants"
    default: op
    children:
      antiguest.preventions.actions.sneak: true
      antiguest.preventions.actions.sprint: true
      antiguest.preventions.actions.move: true
  antiguest.preventions.actions.music:
    description: "Allows the player to do music related things"
    default: op
    children:
      antiguest.preventions.actions.noteblock: true
      antiguest.preventions.actions.jukebox: true
  antiguest.bucket:
    description: "Allows the player to use buckets"
    default: op
    children:
      antiguest.preventions.actions.lavabucket: true
      antiguest.preventions.actions.waterbucket: true