name: AntiGuest
main: de.codeinfection.quickwango.AntiGuest.AntiGuest
version: "${project.version}"
authors:
  - "Quick_Wango"
description: "Prevents guests from griefing."
website: "http://parallel-universe.de"
depend:
  - Permissions