name: AntiGuest
version: "${project.version}"
main: de.codeinfection.quickwango.AntiGuest.AntiGuestBukkit
dev-url: http://dev.bukkit.org/server-mods/antiguest
authors:
  - "Quick_Wango"
description: "Prevents guests from griefing."
website: "http://parallel-universe.de"
commands:
  antiguest:
    usage: "/<command> <subcommand> [arguments...]"
    description: "This is the base command for all AntiGuest commands"
    aliases:
      - ag
permissions:
  antiguest.*:
    description: "Allows the player to do everything"
    default: op
    children:
      antiguest.preventions.*: true
      antiguest.commands.*: true
