name: AntiGuest
main: de.codeinfection.quickwango.AntiGuest.AntiGuest
version: "${project.version}"
authors:
  - "Quick_Wango"
description: "Prevents guests from griefing."
website: "http://parallel-universe.de"
softdepend:
  - Permissions
permissions:
  AntiGuest.*:
    description: "Allows the player to do everything"
    default: op
    children:
      AntiGuest.build: true
      AntiGuest.interact: true
      AntiGuest.pvp: true
      AntiGuest.pickup: true
      AntiGuest.vehicle: true
      AntiGuest.spam: true
  AntiGuest.build:
    description: "Allows the player to build"
    default: op
  AntiGuest.interact:
    description: "Allows the player to interact with the world"
    default: op
  AntiGuest.pvp:
    description: "Allows the player to fight"
    default: op
  AntiGuest.pickup:
    description: "Allows the player to pickup items"
    default: op
  AntiGuest.vehicle:
    description: "Allows the player to pickup items"
    default: op
  AntiGuest.spam:
    description: "Allows the player to chat as fast as he wants"
    default: op